# Generated by Django 3.1.6 on 2021-03-29 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tleague', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(default=' ', max_length=100, on_delete=django.db.models.deletion.SET_DEFAULT, to='tleague.team'),
        ),
    ]
