# Generated by Django 3.1.6 on 2021-04-10 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handicap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handicap', models.IntegerField(blank=True, default=0, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tleague.player', to_field='full_name')),
            ],
        ),
    ]
