# Generated by Django 3.1.6 on 2021-03-23 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team', models.CharField(default='', max_length=150, primary_key=True, serialize=False)),
                ('points', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='handicap_number',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.AddField(
            model_name='player',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='initial_handicap',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tleague.player'),
        ),
        migrations.AlterField(
            model_name='league',
            name='contestants',
            field=models.ManyToManyField(blank=True, to='tleague.Player'),
        ),
        migrations.AlterField(
            model_name='score',
            name='contestant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tleague.player'),
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
        migrations.AddField(
            model_name='player',
            name='team_name',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='tleague.team', verbose_name='Team'),
        ),
    ]
