# Generated by Django 3.1.6 on 2021-03-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tleague', '0002_auto_20210323_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='player',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='player',
            name='team_name',
            field=models.CharField(default=' ', max_length=100, verbose_name='Team'),
        ),
    ]
