# Generated by Django 3.1.6 on 2021-03-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pdga_number',
            new_name='handicap_number',
        ),
    ]
