# Generated by Django 3.1.6 on 2021-03-06 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contestant_course_hole_layout_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contestant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contestant')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.course')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.layout')),
                ('scores', models.ManyToManyField(blank=True, to='accounts.Score')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Name of event, eg 'September League Day'", max_length=50, null=True)),
                ('date', models.DateTimeField()),
                ('rounds', models.IntegerField(help_text='Number of rounds that players are required to complete during this league event')),
                ('awards', models.ManyToManyField(blank=True, to='accounts.Award')),
                ('cards', models.ManyToManyField(blank=True, to='accounts.Card')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('league_points', models.CharField(default='10,9,8,7,6,5,4,3,2,1', help_text='\nPoints assignments for league event ranking (based on HC adjusted total score).\nIndex of list is rank, value is points earned. Last element of list is used as the\nminimum attainable points for a contestant who does not complete a league event, or\nwho does not yet have enough rounds recorded in league to calculate a HC. Must be a comma separated list of integers.\n            ', max_length=50, verbose_name='League Points Assignment')),
                ('handicap_multiplier', models.FloatField(default=0.8, help_text="\nA value that is multiplied against a contestant's raw HC delta average. The result of this calculation becomes the contestant's current HC.")),
                ('handicap_min_rounds', models.IntegerField(default=2, help_text='\nThe minimum number of rounds required before a HC is evaluated for a contestant if they\ndo not have an initial HC. The contestant will still earn min attainable points for\nthe league attendance even without an initial HC while they are accruing the requisite\nnumber of rounds for a HC. Previous events will be retro-calculated using newly calculated\nHC meaning points and ranks will move in retrospect when a contestant finally plays enough rounds to get a HC.\n', verbose_name='Min rounds for HC')),
                ('handicap_min_rounds_avg', models.IntegerField(default=5, help_text="\nThe max number of best score cards to use to calculate a player's current HC\n", verbose_name='Best Cards to use for HC')),
                ('handicap_max_rounds_avg', models.IntegerField(default=8, help_text='\nThe number of past cards to consider when chosing the best cards for a player for their HC calculation. This value needs to be larger than the number of best cards used for HC calculation above.\n', verbose_name='Max Cards to consider for HC')),
                ('contestants', models.ManyToManyField(blank=True, to='accounts.Contestant')),
                ('events', models.ManyToManyField(blank=True, to='accounts.Event')),
            ],
        ),
    ]
