# Generated by Django 3.1.6 on 2021-03-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_award_card_event_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='course',
        ),
        migrations.RemoveField(
            model_name='card',
            name='layout',
        ),
        migrations.RemoveField(
            model_name='card',
            name='scores',
        ),
        migrations.RemoveField(
            model_name='contestant',
            name='player',
        ),
        migrations.RemoveField(
            model_name='course',
            name='layouts',
        ),
        migrations.RemoveField(
            model_name='event',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='event',
            name='cards',
        ),
        migrations.RemoveField(
            model_name='layout',
            name='holes',
        ),
        migrations.RemoveField(
            model_name='league',
            name='contestants',
        ),
        migrations.RemoveField(
            model_name='league',
            name='events',
        ),
        migrations.RemoveField(
            model_name='score',
            name='contestant',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='Contestant',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Hole',
        ),
        migrations.DeleteModel(
            name='Layout',
        ),
        migrations.DeleteModel(
            name='League',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Score',
        ),
    ]
